export const FETCH_PRODUCTS_LIST = "FETCH_PRODUCTS_LIST";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const SET_QUANTITY = "SET_QUANTITY";
export const EMPTY_CART = "EMPTY_CART";
